name = "PeriLab"
uuid = "2ecefcea-59f0-46dd-9cfd-1d2b8cc5f112"
authors = ["Christian Willberg <christian.willberg@dlr.de>", "Jan-Timo Hesse <jan-timo.hesse@dlr.de>"]
version = "1.4.10"

[deps]
AbaqusReader = "bc6b9049-e460-56d6-94b4-a597b2c0390d"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Exodus = "f57ae99e-f805-4780-bdca-96e224be1e5a"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LazyGrids = "7031d0ef-c40d-4431-b2f8-61a8d2f650db"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PointNeighbors = "1c4d5385-0a27-49de-8e2c-43b175c8985c"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
ZipArchives = "49080126-0e18-4c2a-b176-c102e4b3760c"

[compat]
AbaqusReader = "0.2.6"
Aqua = "0.8"
ArgParse = "1"
CDDLib = "0.10.1"
CSV = "0.10"
Combinatorics = "1"
DataFrames = "1"
DataStructures = "0.18"
Dates = "1"
Dierckx = "0.5"
Exodus = "0.13"
FastGaussQuadrature = "1"
JSON3 = "1"
LazyGrids = "1"
LibGit2 = "1"
LinearAlgebra = "1"
Logging = "1"
LoggingExtras = "1"
LoopVectorization = "0.12"
MPI = "0.20"
MPIPreferences = "0.1"
Meshes = "0.51, 0.53, 0.54"
NLsolve = "4.5"
NearestNeighbors = "0.4"
OrderedCollections = "1"
Pkg = "1"
PointNeighbors = "0.4, 0.5, 0.6"
Polyhedra = "0.8.1"
PrettyTables = "2"
Printf = "1"
ProgressBars = "1"
Random = "1"
Rotations = "1"
SparseArrays = "1.11.0"
StaticArrays = "1"
Statistics = "1"
StyledStrings = "1"
Test = "1"
TestSetExtensions = "3"
TimerOutputs = "0.5"
Unitful = "1.22"
YAML = "0.4"
ZipArchives = "1, 2"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[targets]
test = ["Aqua", "JSON3", "Logging", "MPI", "Test", "TestSetExtensions"]
