# SPDX-FileCopyrightText: 2023 Christian Willberg <christian.willberg@dlr.de>, Jan-Timo Hesse <jan-timo.hesse@dlr.de>
#
# SPDX-License-Identifier: BSD-3-Clause

blank_issues_enabled: false
contact_links:
  - name: â“ Discussion
    url: https://github.com/PeriHub/PeriLab.jl/discussions/new/choose
    about: Please ask and answer questions here. ğŸ¥
